from django.conf.urls.defaults import patterns  # , include
from provisionadmin.service.views import gesture
from django.views import static
from provisionadmin.service.views import resource

urlpatterns = patterns(
    'provisionadmin.service.views',
    (r'^media/(?P<path>.*)$', static.serve,
        {'document_root': '/var/app/data/provisionadmin-service'}),
    (r'^login', 'user.login'),
    (r'^logout', 'user.logout'),
    (r'^aosgesture/add', gesture.preset_add_gesture),
    (r'^aosgesture/update', gesture.preset_modify_gesture),
    (r'^aosgesture/delete', gesture.preset_delete_gesture),
    (r'^aosgesture/upload', gesture.preset_upload_gesture),
    (r'^icon/add', resource.preset_add_icon),
    (r'^icon/edit', resource.preset_edit_icon),
    (r'^icon/update', resource.preset_update_icon),
    (r'^icon/list', resource.preset_icon_list),
    (r'^icon/upload', resource.preset_upload_icon),
    (r'^icon/delete', resource.preset_delete_icon),
    (r'^icon/getDisplayData', resource.get_icon_display_data),
    (r'^auth/user/add', 'user.create_user'),
    (r'^auth/user/(?P<user_id>[1-9]\d*)', 'user.detail_modify_user'),
    (r'^auth/user/delete', 'user.delete_user'),
    (r'^auth/user/list', 'user.list_user'),
    (r'^auth/group/add', 'user.create_group'),
    (r'^auth/group/(?P<group_id>[1-9]\d*)', 'user.detail_modify_group'),
    (r'^auth/group/delete', 'user.delete_group'),
    (r'^auth/group/list', 'user.list_group'),
    (r'^auth/perm/add', 'user.create_perm'),
    (r'^auth/perm/(?P<perm_id>[1-9]\d*)', 'user.detail_modify_perm'),
    (r'^auth/perm/delete', 'user.delete_perm'),
    (r'^auth/perm/list', 'user.list_perm'),
    (r'^auth/user/active', 'user.user_active'),
    (r'^auth/user/permissions', 'user.user_perm_list'),
    (r'^auth/group/permissions', 'user.group_perm_list'),
    (r'^auth/actionlog/list', 'user.action_log_list'),
    (r'^changepwd', 'user.change_password'),
    (r'^aospredata/delete', 'preset.preset_predata_delete'),
    (r'^aospredata/upload', 'preset.upload_predata'),
    (r'^aospredata/export', 'preset.export_predata'),
    (r'^aospredata/byrule', 'preset.export_predata_by_rule'),
    (r'^aospredata/dataexport', 'preset.export_byrule'),
    (r'^(?P<model_name>[A-Za-z]+)/add', 'preset.preset_model_add'),
    (r'^(?P<model_name>[A-Za-z]+)/delete', 'preset.preset_model_delete'),
    (r'^(?P<model_name>[A-Za-z]+)/list', 'preset.preset_model_list'),
    (r'^(?P<model_name>[A-Za-z]+)/edit', 'preset.preset_model_detail'),
    (r'^(?P<model_name>[A-Za-z]+)/update', 'preset.preset_model_modify'),
)
